{
 "title": "Traffic (ClickHouse)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Instant traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT\n    t,\n    sum(sumbytes) AS sumbytes\nFROM (\n    SELECT\n        $timeSeries AS t,\n        sum(bytes*sampling_rate) as sumbytes\n    FROM $table\n    WHERE $timeFilter\n    GROUP BY t\n\n    UNION ALL\n\n    SELECT\n        toInt64(intDiv($from+number*$interval, $interval)*$interval*1000) AS t,\n        0 AS sumbytes\n    FROM numbers(intDiv($to-$from, $interval))\n)\nGROUP BY t\nORDER BY t",
     "query": "SELECT\n  toStartOfInterval(ts, INTERVAL 1 minute) AS t,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime($__from/1000) AND toDateTime($__to/1000)\nGROUP BY t\nORDER BY t\n",
     "rawQuery": "SELECT\n  toStartOfInterval(ts, INTERVAL 1 minute) AS t,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime(1756139236550/1000) AND toDateTime(1756139536550/1000)\nGROUP BY t\nORDER BY t",
     "round": "0s",
     "select": [
      [
       { "params": [ "bytes" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top source IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  dst_addr AS dstip,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime($__from/1000) AND toDateTime($__to/1000)\nGROUP BY dstip\nORDER BY sumbytes DESC\nLIMIT 10\n",
     "rawQuery": "SELECT\n  dst_addr AS dstip,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime(1756139683883/1000) AND toDateTime(1756139983883/1000)\nGROUP BY dstip\nORDER BY sumbytes DESC\nLIMIT 10",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Top source ports",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(src_port) as port,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY port\nORDER BY sumbytes DESC",
     "query": "SELECT\n  concat(toString(proto), '/', toString(src_port)) AS port,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime($__from/1000) AND toDateTime($__to/1000)\nGROUP BY port\nORDER BY sumbytes DESC\nLIMIT 10\n",
     "rawQuery": "SELECT\n  concat(toString(proto), '/', toString(src_port)) AS port,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime(1756139269927/1000) AND toDateTime(1756139569927/1000)\nGROUP BY port\nORDER BY sumbytes DESC\nLIMIT 10",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top destination IPs",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT\n    if(etype = 0x800, IPv4NumToString(reinterpretAsUInt32(substring(reverse(dst_addr), 13,4))), IPv6NumToString(dst_addr)) as dstip,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY dstip\nORDER BY sumbytes DESC",
     "query": "SELECT\n  dst_addr AS dstip,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime($__from/1000) AND toDateTime($__to/1000)\nGROUP BY dstip\nORDER BY sumbytes DESC\nLIMIT 10\n",
     "rawQuery": "SELECT\n  dst_addr AS dstip,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime(1756139299032/1000) AND toDateTime(1756139599032/1000)\nGROUP BY dstip\nORDER BY sumbytes DESC\nLIMIT 10",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  },
  {
   "title": "Top destination ports",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "database": "default",
     "dateColDataType": "date",
     "dateTimeColDataType": "time_flow_start_ns",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "WITH dictGetString('dictionaries.protocols', 'name', toUInt64(proto)) AS protoName\nSELECT\n    if(protoName = '', toString(proto), protoName) || '/' || toString(dst_port) as port,\n    sum(bytes*sampling_rate) AS sumbytes\nFROM $table\nWHERE $timeFilter\nGROUP BY port\nORDER BY sumbytes DESC",
     "query": "SELECT\n  concat(toString(proto), '/', toString(dst_port)) AS port,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime($__from/1000) AND toDateTime($__to/1000)\nGROUP BY port\nORDER BY sumbytes DESC\nLIMIT 10\n",
     "rawQuery": "SELECT\n  concat(toString(proto), '/', toString(dst_port)) AS port,\n  sum(bytes) AS sumbytes\nFROM default.flows_raw\nWHERE ts BETWEEN toDateTime(1756139322246/1000) AND toDateTime(1756139622246/1000)\nGROUP BY port\nORDER BY sumbytes DESC\nLIMIT 10",
     "round": "0s",
     "select": [
      [
       { "params": [ "value" ], "type": "column" }
      ]
     ],
     "table": "flows_raw",
     "where": [
      {
       "name": "$__timeFilter",
       "params": [],
       "type": "macro"
      }
     ]
    }
   ]
  }
 ]
}