apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    uid: clickhouse_ds
    isDefault: false
    jsonData:
      defaultDatabase: default
      port: 9000
      server: clickhouse
      protocol: native
    secureJsonData:
      password: ""
    user: default

  - name: Prometheus
    type: prometheus
    access: proxy
    uid: prometheus_ds
    isDefault: true
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
